{
 "title": "Asterisk - Logs",
 "tags": [ "asterisk-integration" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "loki_datasource", "label": "Data Source", "query": "loki" },
   { "name": "job", "label": "Job", "query": "label_values(job)" },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values({job=~\"$job\"}, instance)"
   },
   { "name": "filename", "label": "File Name", "query": "label_values(filename)" }
  ]
 },
 "panels": [
  { "title": "Logs Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 3 },
   "options": {
    "content": "<img style=\"margin: 20px;\" src=\"https://storage.googleapis.com/grafanalabs-integration-logos/asterisk.png\">"
   }
  },
  {
   "title": "Total Log Lines",
   "type": "stat",
   "description": "Total number of log lines",
   "gridPos": { "h": 4, "w": 3, "x": 4, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "count_over_time({job=\"$job\", filename=\"$filename\"}[$__interval])"
    }
   ]
  },
  {
   "title": "Warnings",
   "type": "stat",
   "description": "Total number of log lines with the type \"WARNING\"",
   "gridPos": { "h": 4, "w": 3, "x": 7, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "count_over_time({job=\"$job\", instance=~\"$instance\", filename=\"$filename\"} |= \"WARNING\" [$__interval])"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "stat",
   "description": "Total number of log lines with the type \"ERROR\"",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "count_over_time({job=\"$job\", instance=~\"$instance\", filename=\"$filename\"} |= \"ERROR\" [$__interval])"
    }
   ]
  },
  {
   "title": "Error Percentage",
   "type": "stat",
   "description": "Total number of log lines with the type \"ERROR\"",
   "gridPos": { "h": 4, "w": 4, "x": 13, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "( count_over_time({job=\"$job\", instance=~\"$instance\", filename=\"$filename\"} |= \"ERROR\" [$__interval]) / count_over_time({job=\"$job\", instance=~\"$instance\", filename=\"$filename\"} [$__interval]) )"
    }
   ]
  },
  {
   "title": "Bytes Used",
   "type": "stat",
   "description": "Total number of bytes used by the log file in the time period",
   "gridPos": { "h": 4, "w": 4, "x": 17, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "bytes_over_time({job=\"$job\", instance=~\"$instance\", filename=\"$filename\"} [$__interval])"
    }
   ]
  },
  {
   "title": "Historical Logs / Warnings / Errors",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count_over_time({job=\"$job\", instance=~\"$instance\", filename=\"$filename\"}[$__interval])"
    },
    {
     "expr": "count_over_time({job=\"$job\", instance=~\"$instance\", filename=\"$filename\"} |= \"WARNING\" [$__interval])"
    },
    {
     "expr": "count_over_time({job=\"$job\", instance=~\"$instance\", filename=\"$filename\"} |= \"ERROR\" [$__interval])"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Errors",
     "type": "logs",
     "description": "Errors from the log file",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 13 },
     "targets": [
      {
       "expr": "{job=~\"$job\", instance=~\"$instance\", filename=~\"$filename\"} |= \"ERROR\""
      }
     ]
    }
   ]
  },
  {
   "title": "Warnings",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Warnings",
     "type": "logs",
     "description": "Warnings from the log file",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 14 },
     "targets": [
      {
       "expr": "{job=~\"$job\", instance=~\"$instance\", filename=~\"$filename\"} |= \"WARNING\""
      }
     ]
    }
   ]
  },
  {
   "title": "Complete Log File",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Full Log File",
     "type": "logs",
     "description": "*Asterisk Full Log File* The \"full\" log is the most detailed, describing each call in great detail.",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 16 },
     "targets": [
      {
       "expr": "{job=~\"$job\", instance=~\"$instance\", filename=~\"$filename\"}"
      }
     ]
    }
   ]
  }
 ]
}