---
- name: Install GPG and CA dependencies
  apt:
    name: [ca-certificates, gnupg]
    state: present

- name: Add Docker GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker stable repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present

- name: Install Docker Engine and Compose Plugin
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
      - python3-docker # Required for Ansible to talk to Docker
    state: present
    update_cache: yes

- name: Ensure Docker service is enabled and running
  service:
    name: docker
    state: started
    enabled: yes